### ISSUE TITLE
Problems with Get Started Easily

### ISSUE THREAD

**Issue by ktodyruik** [fsbolero/Bolero#114]
Hi,

I'm trying out Bolero. Looks interesting. Unfortunately my first try at this failed.

Followed the `Get Started Easily` instructions

```
dotnet new -i Bolero.Templates
dotnet new bolero-app -o MyApp
dotnet run -p src/MyApp.Server
```

Here was the result of the run command

```
$ dotnet run -p src/MyApp.Server
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyApp.Server.Program.main(String[] args) in /home/kerry/Projects/MyApp/src/MyApp.Server/Startup.fs:line 51
```

Here is my system info:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tarmil** [comment]
Yes, this is a problem with the latest release that I'll fix very quickly. In the meantime you can explicitly install the correct versions of dependencies:

```
dotnet add src/MyApp.Client package Microsoft.AspNetCore.Components -v 3.1.1
dotnet add src/MyApp.Client package Microsoft.AspNetCore.Components.Web -v 3.1.1
```

**Comment by ktodyruik** [comment]
Thanks! Did as you suggested. Now getting the following:

```
$ dotnet run -p src/MyApp.Server
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.SignalR.Protocols.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.AspNetCore.SignalR.Protocols.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Bolero.Templating.Server.ServerTemplatingExtensions.AddHotReload(IServiceCollection this, FSharpOption`1 templateDir)
   at MyApp.Server.Startup.ConfigureServices(IServiceCollection services) in /home/kerry/Projects/MyApp/src/MyApp.Server/Startup.fs:line 20
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyApp.Server.Program.main(String[] args) in /home/kerry/Projects/MyApp/src/MyApp.Server/Startup.fs:line 51
```

**Comment by OnurGumus** [comment]
@ktodyruik while you are waiting for a fix, you can check out 
https://github.com/OnurGumus/FBlazorShop
It uses latest bolero/blazor with some issues fixed.

**Comment by OnurGumus** [comment]
@Tarmil may I suggest adding a link to my project as a show case :)

**Comment by tofraley** [comment]
I had the exact same series of problems on both Manjaro and Ubuntu.  I found adding `-v m` at the end of my `dotnet run` helped me figure it out.  It looked like the Protocols.SignalR assembly wasn't found because there were  conflicting versions of the package (referenced below) installed.  At any rate, I installed the two pacakges that @Tarmil mentioned, as well as this package to my client app and it worked:
`dotnet add src/MyApp.Client package Microsoft.AspNetCore.SignalR.Client.Core -v 3.1.1`

**Comment by Tarmil** [comment]
Right, this is the same problem as above but with the HotReload package's dependencies.

**Comment by Tarmil** [comment]
This should hopefully be solved with Bolero 0.11.22.

**Comment by tofraley** [comment]
I can confirm it looks resolved, for me at least.  I was able to start a new project, change the versions of Bolero and Bolero.HotReload, and run the app without needing to add any other packages.

**Comment by Dzoukr** [comment]
Hello, it seems that this problem still remains. I just downloaded latest template, followed the steps and got:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at MyApp.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyApp.Server.Program.main(String[] args) in C:\Dzoukr\MyApp\src\MyApp.Server\Startup.fs:line 53
```

**Comment by Dzoukr** [comment]
Please, any idea how to resolve it, @Tarmil ?

**Comment by Dzoukr** [comment]
Ok, just had to update to the latest .NET SDK and it works. But this is dll hell (not this library's fault). :(

**Comment by Tarmil** [comment]
Still, indicating on "Get started easily" that you need to ensure you have the right dotnet version would be good. I'll do that ASAP.
